# Generated by Django 3.1.7 on 2021-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_resume_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
